name: Build HMG for Windows 32 MINGW

on:
  push:
    paths: 
      - '.github/workflows/hmg35_32b.yml'

  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        gcc --version
        dir C:\mingw32
    - name: Build HMG
      shell: cmd
      run: |
        move harbour\bin\win\mingw\*.* harbour\bin
        SET PATH=C:\mingw32\bin;%PATH%
        SET HB_COMPILER=mingw
        BuildAllLib32.bat
    - name: Preparing result folders...
      shell: cmd
      run: |
        mkdir result
        mkdir result\harbour\bin
        mkdir result\harbour\contrib
        mkdir result\harbour\doc
        mkdir result\harbour\include
        mkdir result\harbour\lib
        mkdir result\lib
        move harbour\bin\*.* result\harbour\bin
        move harbour\contrib\*.* result\harbour\contrib
        move harbour\doc\*.* result\harbour\doc
        move harbour\include\*.* result\harbour\include   
        move harbour\lib\*.* result\harbour\lib
        move lib\*.* result\lib
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
       name: hmg_win32_mingw
       path: result
