name: HMG 32bit MinGW Windows

on:
    push:

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:    
    - name: Checkout hmg repo
      uses: actions/checkout@v2
      with:
       repository: asistex/HMG
       path: asistex/HMG

    - name: checking dependencies
      run: |
        gcc --version

    - name: Building lib HMG
      shell: cmd
      run: |
        cd asistex\hmg
        set path=c:\mingw32\mingw32\bin;c:\bcd\prg\pcomp\hb32_mgw102\bin;%path%
        libHmgUni.bat

    - name: Create output folders...
      shell: cmd
      run: |
        mkdir output
        mkdir output\hmg
        mkdir output\hmg\lib
        move hmg\lib\*.a output\lib

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Create artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: hmg_win32_mingw_${{ env.TIME }}
       path: output
