name: Build HMG for Windows 32 mingw

on:
    push:

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:    
    - name: Checkout hmg repo
      uses: actions/checkout@v2
      with:
       repository: HMG-Official/HMG
       path: HMG-Official/HMG

    - name: Install dependencies
      run: |
        gcc --version
        dir C:\mingw32

    - name: Building HMG
      shell: cmd
      run: |
        move harbour\bin\win\mingw\*.* harbour\bin
        set path=C:\mingw32\bin;%path%
        echo %path%
        SET HB_COMPILER=mingw
        BuildAllLib32.bat

    - name: Preparing result folders...
      shell: cmd
      run: |
        mkdir result
        mkdir result\hmg\lib
        move hmg\lib\*.* result\hmg\lib
        move lib\*.* result\lib

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
       name: hmg35_32b
       path: result
